# frozen_string_literal: true

module RuboCop
  module Extension
    module Generator
      class Generator
        def initialize(name)
          @name = name
        end

        def generate
          system('bundle', 'gem', name, exception: true)

          put "lib/#{name}.rb", <<~RUBY
            # frozen_string_literal: true

            require 'rubocop'

            require_relative '#{dirname}'
            require_relative '#{dirname}/version'
            require_relative '#{dirname}/plugin'

            require_relative '#{cops_file_name.sub(/\.rb$/, '').sub(%r{^lib/}, '')}'
          RUBY

          put "lib/#{dirname}/plugin.rb", <<~RUBY
            # frozen_string_literal: true

            require 'lint_roller'

            module RuboCop
              module #{classname}
                # A plugin that integrates #{name} with RuboCop's plugin system.
                class Plugin < LintRoller::Plugin
                  def about
                    LintRoller::About.new(
                      name: '#{name}',
                      version: VERSION,
                      homepage: "TODO: Put your plugin's homepage URL here.",
                      description: "TODO: Put your plugin's description here."
                    )
                  end

                  def supported?(context)
                    context.engine == :rubocop
                  end

                  def rules(_context)
                    LintRoller::Rules.new(
                      type: :path,
                      config_format: :rubocop,
                      value: Pathname.new(__dir__).join('../../../config/default.yml')
                    )
                  end
                end
              end
            end
          RUBY

          put cops_file_name, <<~RUBY
            # frozen_string_literal: true
          RUBY

          put "config/default.yml", <<~YAML
            # Write it!
          YAML

          put 'spec/spec_helper.rb', <<~RUBY
            # frozen_string_literal: true

            require '#{name}'
            require 'rubocop/rspec/support'

            RSpec.configure do |config|
              config.disable_monkey_patching!
              config.raise_errors_for_deprecations!
              config.raise_on_warning = true
              config.fail_if_no_examples = true

              config.order = :random
              Kernel.srand config.seed
            end
          RUBY

          put '.rspec', <<~TEXT
            --format documentation
            --color
            --require spec_helper
          TEXT

          put '.rubocop.yml', <<~YML
            plugins:
              - rubocop-internal_affairs

            Naming/FileName:
              Exclude:
                - lib/#{name}.rb
          YML

          patch "lib/#{dirname}.rb", 'module Rubocop', 'module RuboCop'
          patch "lib/#{dirname}/version.rb", 'module Rubocop', 'module RuboCop'
          patch 'README.md', 'Rubocop', 'RuboCop'
          patch "#{name}.gemspec", 'Rubocop', 'RuboCop'
          patch "#{name}.gemspec", /required_ruby_version = ">= \d.\d.\d"/, 'required_ruby_version = ">= 2.7.0"'
          patch "#{name}.gemspec", /^end/, <<~RUBY

              spec.metadata['default_lint_roller_plugin'] = 'RuboCop::#{classname}::Plugin'

              spec.add_dependency 'lint_roller', '~> 1.1'
              spec.add_dependency 'rubocop', '>= 1.72.2'
            end
          RUBY

          patch "Rakefile", /\z/, <<~RUBY

            require 'rspec/core/rake_task'

            RSpec::Core::RakeTask.new(:spec) do |spec|
              spec.pattern = FileList['spec/**/*_spec.rb']
            end

            desc 'Generate a new cop with a template'
            task :new_cop, [:cop] do |_task, args|
              require 'rubocop'

              cop_name = args.fetch(:cop) do
                warn 'usage: bundle exec rake new_cop[Department/Name]'
                exit!
              end

              generator = RuboCop::Cop::Generator.new(cop_name)

              generator.write_source
              generator.write_spec
              generator.inject_require(root_file_path: '#{cops_file_name}')
              generator.inject_config(config_file_path: 'config/default.yml')

              puts generator.todo
            end
          RUBY

          patch 'Gemfile', /\z/, <<~RUBY
            gem 'rubocop', '>= 1.72.2'
            gem 'rspec'
          RUBY

          if Gem::Version.new(Bundler::VERSION) >= Gem::Version.new('2.3.9')
            patch 'README.md', /\$ bundle add (.*)$/, '$ bundle add \1 --require=false'
          else
            patch 'README.md', /^gem '#{name}'$/, "gem '#{name}', require: false"
          end

          # NOTE: Since useful type definitions are usually not provided, they are not generated by default.
          # Users can create them as needed.
          delete "sig"

          puts
          puts <<~MESSAGE
            It's done! You can start developing a new extension of RuboCop in #{root_path}.
            For the next step, you can use the cop generator.

              $ bundle exec rake 'new_cop[#{classname}/SuperCoolCopName]'
          MESSAGE
        end

        private def put(path, content)
          path = root_path / path
          puts "create #{path}"
          FileUtils.mkdir_p(path.dirname) unless path.dirname.directory?
          path.write(content)
        end

        private def patch(path, pattern, replacement)
          puts "update #{path}"
          path = root_path / path
          file = path.read
          raise "Cannot apply patch for #{path} because #{pattern} is missing" unless file.match?(pattern)

          path.write file.sub(pattern, replacement)
        end

        private def delete(path)
          puts "delete #{path}"
          path = root_path / path
          FileUtils.rm_r(path)
        end

        private def root_path
          @root_path ||= Pathname(name)
        end

        private def dirname
          @dirname ||= name.sub('-', '/')
        end

        private def classname
          @classname ||= name.split('-').last.camelcase
        end

        private def cops_file_name
          @cops_file_name ||= "lib/rubocop/cop/#{name.split('-').last}_cops.rb"
        end

        attr_reader :name
        private :name
      end
    end
  end
end
